services:
  influx:
    container_name: influxdb
    image: influxdb
    restart: always
    env_file:
      - db.env
    # - db_example.env
    ports:
      - 8086:8086
    volumes:
      - /mnt/usbdrive/docker/data/influxdb/data:/var/lib/influxdb2
      - /mnt/usbdrive/docker/data/influxdb/config:/etc/influxdb2
      - /mnt/usbdrive/docker/data/influxdb/scripts:/docker-entrypoint-initdb.d
    # - influx_data:/var/lib/influxdb2
    # - influx_config:/etc/influxdb2
    # - influx_scripts:/docker-entrypoint-initdb.d



volumes:
  influx_data:
  influx_config:
  influx_scripts:
